### ISSUE TITLE
Where is the module named tools.plot_utils

### ISSUE THREAD

**Issue by gnorZgnoD** [RookieJunChen/Inter-SubNet#1]
An error happened when i run this code:
ModuleNotFoundError: No module named 'tools.plot_utils'

**Comment by RookieJunChen** [comment]
Can you provide more detailed information about the error reporting? For example, which line of code in which python script file causes this problem?

**Comment by gnorZgnoD** [comment]
Hi Rookie,


&nbsp; Thank for your quick reply, the attachment displaies the details of the error happened to me.


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RookieJunChen/Inter-SubNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月14日(星期天) 晚上11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RookieJunChen/Inter-SubNet] Where is the module named tools.plot_utils (Issue #1)





 
Can you provide more detailed information about the error reporting? For example, which line of code in which python script file causes this problem?

**Comment by RookieJunChen** [comment]
I'm sorry that what you replied to me seems to be a bunch of garbled codes.
I have corrected the issue where there may be a No module named 'tools.plot_utils'. You can test the latest version of code in this github repository.

**Comment by gnorZgnoD** [comment]
Much appreciated.
