### ISSUE TITLE
About the pre-training model

### ISSUE THREAD

**Issue by KarmaYan** [RookieJunChen/Inter-SubNet#4]
First of all, thank you for your work. I would like to ask if it is possible to provide a pre-trained model to test the optimal performance of this algorithm.

**Comment by RookieJunChen** [comment]
As mentioned in the README, the pre-trained checkpoint can be obtained from [checkpoint](https://drive.google.com/file/d/1j9jdXRxPhXLE93XlYppCQtcOqMOJNjdt/view?usp=share_link).
For more details about usage, please also check README carefully.

**Comment by KarmaYan** [comment]
> As mentioned in the README, the pre-trained checkpoint can be obtained from [checkpoint](https://drive.google.com/file/d/1j9jdXRxPhXLE93XlYppCQtcOqMOJNjdt/view?usp=share_link). For more details about usage, please also check README carefully.

Thank you for your reply. Because there is no VPN, I cannot access that web page, so I would like to ask again if there is another storage checkpoint address.
If not，it doesn't matter.

**Comment by RookieJunChen** [comment]
Could you offer me your email? I can also send the ckpt to you by email.

**Comment by KarmaYan** [comment]
> Could you offer me your email? I can also send the ckpt to you by email.
407621834@qq.com
Thank You！
